import { AlertTriangle, Download, FileText, TrendingUp, X } from "lucide-react";
import { FraudReport } from "@/components/fraud-report";
import { fraudStats, messages, showReports } from "@/signals";
import { parseFraudReport } from "@/utils/parse-fraud-report";

export function FraudReportsViewer() {
  const stats = fraudStats.value;

  // Extract fraud reports from agent messages
  const fraudReports = messages.value
    .filter((m) => m.isAgent() && m.text.includes("FRAUD_REPORT"))
    .map((m, index) => ({
      id: m.id,
      timestamp: m.createdAt,
      index: index + 1,
      content: m.text,
    }))
    .reverse();

  const handleClose = () => {
    showReports.value = false;
  };

  const handleExportAll = () => {
    const exportData = {
      exportDate: new Date().toISOString(),
      totalReports: fraudReports.length,
      stats: {
        totalAnalyzed: stats.totalAnalyzed,
        highRisk: stats.highRisk,
        mediumRisk: stats.mediumRisk,
        lowRisk: stats.lowRisk,
        successRate: stats.successRate,
      },
      reports: fraudReports.map((report) => ({
        id: report.id,
        timestamp: report.timestamp.toISOString(),
        content: report.content,
      })),
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `fraud-reports-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div class="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm animate-fade-in">
      <div class="h-full overflow-y-auto p-4">
        <div class="max-w-5xl mx-auto">
          {/* Header */}
          <div class="bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg p-4 mb-4 transition-colors">
            <div class="flex items-center justify-between">
              <div>
                <h2 class="text-2xl font-bold text-zinc-900 dark:text-white">
                  Fraud Detection Reports
                </h2>
                <p class="text-sm text-zinc-600 dark:text-zinc-400 mt-1">
                  View and export fraud analysis reports generated by the AI
                  agents
                </p>
              </div>
              <button
                onClick={handleClose}
                class="p-2 rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors"
                aria-label="Close reports"
              >
                <X size={20} strokeWidth={2} />
              </button>
            </div>
          </div>

          {/* Summary Stats */}
          <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
            <div class="bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg p-4">
              <div class="flex items-center gap-x-2 mb-2">
                <FileText size={20} class="text-blue-500" />
                <span class="text-sm text-zinc-600 dark:text-zinc-400">
                  Total Reports
                </span>
              </div>
              <p class="text-2xl font-bold text-zinc-900 dark:text-white">
                {fraudReports.length}
              </p>
            </div>
            <div class="bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg p-4">
              <div class="flex items-center gap-x-2 mb-2">
                <AlertTriangle size={20} class="text-red-500" />
                <span class="text-sm text-zinc-600 dark:text-zinc-400">
                  High Risk Cases
                </span>
              </div>
              <p class="text-2xl font-bold text-zinc-900 dark:text-white">
                {stats.highRisk}
              </p>
            </div>
            <div class="bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg p-4">
              <div class="flex items-center gap-x-2 mb-2">
                <TrendingUp size={20} class="text-green-500" />
                <span class="text-sm text-zinc-600 dark:text-zinc-400">
                  Detection Rate
                </span>
              </div>
              <p class="text-2xl font-bold text-zinc-900 dark:text-white">
                {stats.successRate.toFixed(1)}%
              </p>
            </div>
          </div>

          {/* Export Button */}
          {fraudReports.length > 0 && (
            <div class="mb-4 flex justify-end">
              <button
                onClick={handleExportAll}
                class="flex items-center gap-x-2 px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white text-sm font-medium rounded-lg transition-colors"
              >
                <Download size={16} />
                Export All Reports
              </button>
            </div>
          )}

          {/* Reports List */}
          <div class="space-y-4">
            {fraudReports.length === 0 ? (
              <div class="bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg p-12 text-center">
                <FileText
                  size={48}
                  class="mx-auto mb-4 text-zinc-400"
                  strokeWidth={1.5}
                />
                <p class="text-zinc-500 dark:text-zinc-400 mb-2">
                  No fraud reports generated yet
                </p>
                <p class="text-sm text-zinc-400 dark:text-zinc-500">
                  Start analyzing transactions to generate fraud detection
                  reports
                </p>
              </div>
            ) : (
              fraudReports.map((report) => {
                const parsedReport = parseFraudReport(report.content);

                return (
                  <div
                    key={report.id}
                    class="bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-lg p-4 transition-colors hover:border-indigo-400 dark:hover:border-indigo-500"
                  >
                    <div class="flex items-center justify-between mb-3">
                      <div class="flex items-center gap-x-2">
                        <FileText
                          size={16}
                          class="text-indigo-500"
                          strokeWidth={2}
                        />
                        <h3 class="text-sm font-semibold text-zinc-900 dark:text-white">
                          Report #{report.index}
                        </h3>
                      </div>
                      <span class="text-xs text-zinc-500 dark:text-zinc-400">
                        {report.timestamp.toLocaleString()}
                      </span>
                    </div>
                    <div class="text-sm">
                      {parsedReport ? (
                        <FraudReport {...parsedReport} />
                      ) : (
                        <div class="whitespace-pre-wrap text-zinc-700 dark:text-zinc-300">
                          {report.content}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
